apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-user-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-user-api
      app.kubernetes.io/instance: demo-user-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-user-api
        app.kubernetes.io/instance: demo-user-api
    spec:
      containers:
      - name: demo-user-api
        image: demo-user-api:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 30
          initialDelaySeconds: 75
          timeoutSeconds: 20
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          periodSeconds: 30
          initialDelaySeconds: 60
          timeoutSeconds: 20
          failureThreshold: 5
