apiVersion: v1
kind: Service
metadata:
  name: demo-user-api
spec:
  selector:
    app.kubernetes.io/name: demo-user-api
    app.kubernetes.io/instance: demo-user-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
