apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base


transformers:
- custom-global-labels.yaml

patchesStrategicMerge:
- custom-resources.yaml
- custom-replica-and-rollout-strategy.yaml

images:
- name: demo-user-api
  newName: jonghak/demo-user-api
  newTag: develop-24bc07f

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: demo-user-api
    app.kubernetes.io/name: demo-user-api
